-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 14:13:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hack_bowl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hack_bowl` DEFAULT CHARACTER SET utf8 ;
USE `hack_bowl` ;

-- -----------------------------------------------------
-- Table `hack_bowl`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`user` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'ユーザID',
  `name` VARCHAR(128) NOT NULL COMMENT 'ユーザ名',
  `email` VARCHAR(128) NOT NULL COMMENT 'メールアドレス',
  `password` VARCHAR(128) NOT NULL COMMENT 'パスワード',
  `auth_token` VARCHAR(128) NOT NULL COMMENT '認証トークン',
  PRIMARY KEY (`id`),
  INDEX `idx_authToken` (`auth_token` ASC))
ENGINE = InnoDB
COMMENT = 'ユーザ';

-- -----------------------------------------------------
-- Table `hack_bowl`.`mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`mentor` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'メンターID',
  `name` VARCHAR(128) NOT NULL COMMENT 'メンター名',
  `email` VARCHAR(128) NOT NULL COMMENT 'メールアドレス',
  `password` VARCHAR(128) NOT NULL COMMENT 'パスワード',
  `auth_token` VARCHAR(128) NOT NULL COMMENT '認証トークン',
  PRIMARY KEY (`id`),
  INDEX `idx_authToken` (`auth_token` ASC))
ENGINE = InnoDB
COMMENT = 'メンター';

-- -----------------------------------------------------
-- Table `hack_bowl`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`position` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'ポジションID',
  `position_name` VARCHAR(64) NOT NULL COMMENT 'ポジション名',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'ポジション';

-- -----------------------------------------------------
-- Table `hack_bowl`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`skill` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'スキルID',
  `skill_name` VARCHAR(64) NOT NULL COMMENT 'スキル名',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'スキル';

-- -----------------------------------------------------
-- Table `hack_bowl`.`project_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`project_user` (
  `project_id` MEDIUMINT NOT NULL COMMENT 'プロジェクトID',
  `user_id` MEDIUMINT NOT NULL COMMENT 'ユーザID')
ENGINE = InnoDB
COMMENT = 'プロジェクトユーザ';

-- -----------------------------------------------------
-- Table `hack_bowl`.`project_mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`project_mentor` (
  `project_id` MEDIUMINT NOT NULL COMMENT 'プロジェクトID',
  `mentor_id` MEDIUMINT NOT NULL COMMENT 'メンターID')
ENGINE = InnoDB
COMMENT = 'プロジェクトメンター';

-- -----------------------------------------------------
-- Table `hack_bowl`.`project_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`project_position` (
  `project_id` MEDIUMINT NOT NULL COMMENT 'プロジェクトID',
  `position_id` MEDIUMINT NOT NULL COMMENT 'ポジションID',
  `limit_num` TINYINT NOT NULL DEFAULT 0 COMMENT 'ポジションの受け入れ人数')
ENGINE = InnoDB
COMMENT = 'プロジェクトポジション';

-- -----------------------------------------------------
-- Table `hack_bowl`.`project_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`project_skill` (
  `project_id` MEDIUMINT NOT NULL COMMENT 'プロジェクトID',
  `skill_id` MEDIUMINT NOT NULL COMMENT 'スキルID')
ENGINE = InnoDB
COMMENT = 'プロジェクトスキル';

-- -----------------------------------------------------
-- Table `hack_bowl`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hack_bowl`.`project` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'プロジェクトID',
  `name` VARCHAR(64) NOT NULL COMMENT 'プロジェクト名',
  `level` INT NOT NULL COMMENT 'レベル感',
  `start_date` DATE COMMENT '開始日')
ENGINE = InnoDB
COMMENT = 'プロジェクト';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
